

	/*------------------------------------------------------+
  	|														|
	|	pseudoRNG + related utilities v0.5 (Feb 26, 2026)	|
	|														|
	+------------------------------------------------------*/


#pragma once


#define __CHAOS_HEADER__			//	In case we need to check later


#include <cstdint>					//	Fixed-width integers; requires C++11
#include <cmath>					//	Math functions
#include "generic.hpp"				//	Generic definitions and useful functions




//
//	For compatibility between various SIMD versions, we run chs::STREAM_NUM parallel 128 bit states (bit streams)
//	initially generated by xoroshiro128's <jump> function from the first one (generated using a hash function).
//	The streams are processed simultaneously, as permitted by the architecture, in chunks of 2 (AVX2), or 4 (AVX512).
//	The states are stored in i64[]; f64[] is used to cache the corresponding Uniform[0,1) numbers.
//	This RNG should provide the same bit sequences regardless of the employed architecture (fp64 values could differ).
//



namespace chs {


	constexpr int STREAM_NUM = 4;						//	Maximal number of bit streams for SIMD processing; should be a power of 2



	//
	//	Object containing the RNG state and functions
	//
	class alignas(__SIMD_ALIGN__) RNG {					//	__SIMD_ALIGN__ from "generic.h"
		private:
			uint64_t		i64[2 * STREAM_NUM] = {0};	//	RNG state; 2 qwords per stream
			fp64_t			f64[STREAM_NUM];			//	U01 random numbers generated from i64[]
			union {										//	Cache for Gaussians; NaN when empty 
				uint64_t	icache = NaN;
				fp64_t 		cache;
			};

			//	Index of the stream for current output; should be in [0..2*STREAM_NUM - 2]
			//	i64[activeStream] and i64[activeStream+1] hold the active RNG state
			int				activeStream = 0;

			//	Advance to the next bit stream;
			//	generate new states in all bit streams and cache f64[] when needed
			void next();

		public:
			//
			//	Basic access functions
			//


			//	Use the following functions to get next 32 or 64 bit integer or 64 bit floating point [0,1) numbers.
			//	These should all be inlined by the compiler.
			uint64_t int64(){					//	random 64 bits (uint64); implicitly inlining
				uint64_t result = i64[activeStream] + i64[activeStream + 1];	//	get uint64 directly from the <state> according to xoroshiro
				next();							//	Move to the next stream; generate new bits if needed
				return result;
			};
			uint32_t int32(){					//	random 32 bits (uint32)
				return int64() >> 32;			//	Top 32 bits should have the best quality
			};
			fp64_t U01(){						//	Uniform[0,1)
				fp64_t result = f64[activeStream >> 1];	//	FP value from the current stream (activeStream points to <states>, must be divided by 2)
				next();							//	Move to the next stream; generate new bits if needed
				return result;
			};

			//
			//	Various distributions
			//
			uint64_t	int64(const uint64_t N);	//	random 64 bit integer in [0..N-1]
			uint32_t	int32(const uint32_t N);	//	random 32 bit integer in [0..N-1] -- slightly faster than int64()
			fp64_t		E1();						//	Exp(1)
			fp64_t		N01();						//	Gaussian with 0 mean and variance 1 via rejection sampling
			fp64_t		n01();						//	Another N(0,1) Gaussian via Box-Muller


			//
			//	Utility functions
			//
			//	Clone the state
			//
			//	Hashing function for seeding the RNG state
			//	<data> is supposed to be 64 bit (8 byte) aligned; <length> >= 8 (in bytes)
			//	WARNING: data is consumed in 64 bit chunks:
			//	...if <length> is not divisible by 8, the left-overs are not utilized
			void hash(const void* data, std::size_t length);


			//
			//	Some extra functions or alternative implementations for testing purposes
			//

			//
			//	Knuth's MMIX RNG: LCG generator employing just i64[0]
			//	Use for testing and benchmarking purposes only: does not invoke next()
			//
			fp64_t U01_lcg(){
				i64[0] = i64[0] * 6364136223846793005 + 1442695040888963407;
				return FP01(i64[0]);
			}

			fp64_t Exp1(){						//	Exp(1) via -log(U01)
				return -log(1.0 - U01());		//	Subtract from 1 to avoid NaN if U01 takes 0 value
			};
			fp64_t qN01();						//	quick "Gaussian" with 0 mean and variance 1 via Binom(64,1/2) approximation
	};





	/*------------------------------------------------------------------------------+
	|																				|
	| 	Mixers: fast hash functions producing "random" output from the <state>		|
	|	These are not necessarily best for RNG when used to produce a sequence		|
	|	of numbers: their primary purpose is to maximize bit mixing (avalanching)	|
	|	after single use...															|
	|																				|
	+------------------------------------------------------------------------------*/




	inline uint8_t mix8(const uint8_t state) {			//	Random stuff: not optimized
		return state * 97 + 111;
	}

	inline uint16_t mix16(const uint16_t state) {		//	Random stuff: not optimized
		return state * 4093 + 32719;
	}


	//
	//	Prospector, https://github.com/skeeto/hash-prospector
	//	Attribution: C. Wellon; public domain
	//	Check the link for even faster mixers with slightly higher bias
	//
	inline uint32_t mix32(uint32_t state) {
		state++;										//	Not needed, but prevents 0->0 and even slightly improves mixing
		state = (state ^ (state >> 17)) * 0xed5ad4bbU;
		state = (state ^ (state >> 11)) * 0xac4c1b51U;
		state = (state ^ (state >> 15)) * 0x31848babU;
		return state ^ (state >> 14);
	}


	//
	//	SplitMix64 algorithm (used, e.g., in Java)
	//	Attribution: S. Vigna, 2015; public domain
	//	NOTE: when SplitMix64() is used as an RNG, 
	//	the new <state> is the incremented value 
	//	from the first line, not the returned value
	//
	inline uint64_t mix64(uint64_t state) {
		state += 0x9e3779b97f4a7c15U;
		state = (state ^ (state >> 30)) * 0xbf58476d1ce4e5b9U;
		state = (state ^ (state >> 27)) * 0x94d049bb133111ebU;
		return state ^ (state >> 31);
	}



}

