

	/*------------------------------------------------------+
	 |														|
	 |	pseudoRNG + related utilities v0.5 (Nov 15, 2025)	|
	 |														|
	 +------------------------------------------------------*/


#pragma once


#define __CHAOS_HEADER__			//	In case we need to check later


#include <cstdint>					//	Fixed-width integers; requires C++11
#include "generic.hpp"				//	Generic definitions and useful functions




//
//	For compatibility between various SIMD versions, we run chs::STREAM_NUM parallel 128 bit states (bit streams)
//	initially generated by xoroshiro128's <jump> function from the first one (generated using a hash function).
//	The streams are processed simultaneously, as permitted by the architecture, in chunks of 2 (AVX2), or 4 (AVX512).
//	The states are stored in i64[]; f64[] is used to cache the corresponding Uniform(0,1) numbers.
//	If random integers are required, draw them directly from i64[] according to xoroshiro's state[0] + state[1]...
//	This RNG should provide the same bit sequences regardless of the employed architecture (fp64 values could differ).
//



namespace chs {


	constexpr int STREAM_NUM = 4;	//	Maximal number of bit streams for SIMD processing; should be a power of 2



	//
	//	Object containing the RNG state and functions
	//
	class alignas(__SIMD_ALIGN__) RNG {					//	__SIMD_ALIGN__ from "generic.h"
		private:
			uint64_t i64[2 * STREAM_NUM] = {0};			//	RNG state; 2 qwords per stream
			fp64_t f64[STREAM_NUM];						//	U01 random numbers generated from i64[]
			union {										//	Cache for Gaussians; NaN when empty 
				uint64_t icache = NaN;
				fp64_t cache;
			};
			int activeStream = 0;						//	Index of the stream for current output; should be in [0..STREAM_NUM-1]

			void next();								//	Generate new states in all bit streams; cache f64[] as well
		public:
			//	Clone the state 
			//
			//	Hashing function for seeding the RNG state
			//	<data> is supposed to be 64 bit (8 byte) aligned; <length> >= 8 (in bytes)
			//	WARNING: data is consumed in 64 bit chunks:
			//	...if <length> is not divisible by 8, the leftovers are not utilized
			void hash(const void* data, std::size_t length);

			fp64_t U01_lcg();				//	Basic LCG for testing/comparison purposes ONLY: modifies i64[0]
			uint64_t int64();				//	random 64 bits (uint64)
			uint64_t int64(uint64_t num);	//	random integer in [0..num-1]
			fp64_t U01();					//	Uniform[0,1)
			fp64_t N01();					//	Gaussian with 0 mean and variance 1 via rejection sampling
			fp64_t qN01();					//	Gaussian with 0 mean and variance 1 via Binom(64,1/2) approximation
			fp64_t n01();					//	Another N(0,1) Gaussian via Box-Muller
	};
	

	/*------------------------------------------------------------------------------+
	 |																				|
	 | 	Mixers: fast hash functions producing "random" output from the <state>		|
	 |	These are not necessarily best for RNG when used to produce a sequence		|
	 |	of numbers: their primary purpose is to maximize bit mixing (avalanching)	|
	 |	after single use...															|
	 |																				|
	 +------------------------------------------------------------------------------*/


	uint8_t		mix8	(uint8_t state);
	uint16_t	mix16	(uint16_t state);
	uint32_t	mix32	(uint32_t state);
	uint64_t	mix64	(uint64_t state);

	static fp64_t		FP01		(uint64_t bits);	//	Convert 64 bit state into [0,1) FP number
	


}

