

	/*------------------------------------------------------+
	 |														|
	 |	pseudoRNG + related utilities v0.5 (Nov 15, 2025)	|
	 |														|
	 +------------------------------------------------------*/


#pragma once


#define __CHAOS_HEADER__			//	In case we need to check later


#include <cstdint>					//	Fixed-width integers; requires C++11
#include "generic.h"				//	Generic definitions and useful functions




//
//	For compatibility between various SIMD versions, we run chs::STREAM_NUM parallel 128 bit states (bit streams)
//	initially generated by xoroshiro128's <jump> function from the first one (generated using a hash function).
//	The streams are generated simultaneously, as permissible by the architecture:
//	in chunks of 2 (AVX2), or 4 (AVX512 -- NOT YET IMPLEMENTED: don't have it on my 258V).
//	An index variable stored in the last 8 bits of the <flags> points to the currently used stream.
//	The RNG should provide the same bit sequences regardless of the employed architecture (fp64 values could differ).
//
//	WARNING: the 4 streams are hard-coded in most algorithms; must look carefully at all code in chaos.cpp if intending to change this number.
//
//	NOTE: Conversion from uint64 into one of the fp64 ranges/types also uses SIMD when available.
//	If the distribution changes in the middle of the "chunk," all cached values are recomputed,
//	e.g., if a Gaussian value is cached but not used, it will be lost after generating some other distribution.
//	



namespace chs {

	//
	//	Random variable distributions:
	//		UInt64		Uniform 64 bit unsigned integer; generated by default
	//		UFP01		Uniform [0,1] IEEE754 64 bit FP value
	enum Distribution {UInt64, UFP01};

	constexpr int STREAM_NUM = 4;	//	Maximal number of bit streams for SIMD processing; should be a power of 2
	constexpr int STATE_SIZE = 16;	//	RNG state size in qwords (64 bit chunks)




	//
	//	Object containing the RNG state and functions
	//
	class alignas(__SIMD_ALIGN__) RNG {					//	__SIMD_ALIGN__ from "generic.h"
		private:
			union {										//	RNG state; 2 qwords per stream
				uint64_t i64[2 * STREAM_NUM] = {0};		//	uint64 view; initialize with 0	
				fp64_t f64[2 * STREAM_NUM];				//	fp64 view
			};
			union {
				uint64_t cui[STREAM_NUM] = {0};			//	RNG cache: uint64 view
				fp64_t cfp[STREAM_NUM];					//	...fp64 view
			};
			int activeStream = 0;						//	Index of the stream for current output; should be in [0..STREAM_NUM-1]
			Distribution activeType = UInt64;			//	...its type; UInt64 is default.
			void next();								//	Generate new states in all bit streams
			//void next(Distribution type);				//	Increment activeStream; call generate() and next() as needed
			void generate(Distribution type);			//	Generate and cache random variables of the given type
		public:
			//	Clone the state 
			//
			//	Hashing function for seeding the RNG state
			//	<data> is supposed to be 64 bit (8 byte) aligned; <length> >= 8 (in bytes)
			//	WARNING: data is consumed in 64 bit chunks:
			//	...if <length> is not divisible by 8, the leftovers are not utilized
			void hash(const void* data, std::size_t length);

			fp64_t U01_lcg();			//	Basic LCG for testing/comparison purposes ONLY: modifies i64[0], no explicit SIMD
			uint64_t int64();			//	random 64 bits
			fp64_t U12();				//	Uniform[1,2)
			fp64_t U01();				//	Uniform[0,1]
			fp64_t N01();				//	Gaussian with 0 mean and variance 1 via rejection sampling
			fp64_t n01();				//	Another N(0,1) Gaussian via Box-Muller
	};
	

	/*------------------------------------------------------------------------------+
	 |																				|
	 | 	Mixers: fast hash functions producing "random" output from the <state>		|
	 |	These are not necessarily best for RNG when used to produce a sequence		|
	 |	of numbers: their primary purpose is to maximize bit mixing (avalanching)	|
	 |	after single use...															|
	 |																				|
	 +------------------------------------------------------------------------------*/


	uint8_t		mix8	(uint8_t state);
	uint16_t	mix16	(uint16_t state);
	uint32_t	mix32	(uint32_t state);
	uint64_t	mix64	(uint64_t state);

	static fp64_t		U01		(uint64_t bits);
	


}

