

	/*------------------------------------------------------+
	 |														|
	 |	pseudoRNG + related utilities v0.3 (Nov 10, 2025)	|
	 |														|
	 +------------------------------------------------------*/


#pragma once

#ifndef __CHAOS_HEADER__
#define __CHAOS_HEADER__


#include <cstdint>					//	Fixed-width integers; requires C++11
#include "generic.h"				//	Some generic definitions




//
//	For compatibility between various SIMD versions (up to AVX512) we always 
//	run 4 parallel 128 bit states, initially generated by xoroshiro128's <jump> function from the first one
//	SIMD versions are computed simultaneously, as available given the architecture; 
//	otherwise the states are updated sequantially providing the same bit sequences regardless of the employed computational model.
//	
#define CHAOS_STATE_SIZE 8			//	State size in qwords
#define CHAOS_CACHE_SIZE 8			//	Cache size in qwords




namespace chs {

	//
	//	Object containing the RNG state
	//
	class alignas(__SIMD_ALIGN__) RNG {
		private:
			uint64_t state[CHAOS_STATE_SIZE] = {0};		//	NOTE: xoroshiro128+ does not change 0
			union {
				uint64_t i64[CHAOS_CACHE_SIZE];			//	A couple qwords to store extra stuff,
				fp64_t f64[CHAOS_CACHE_SIZE];			//	e.g., Gaussian random variables in Box-Muller
			} cache = {.i64 = {NaN}};					//	Initialize with NaN
			int index = 0;								//	{0,1,2,3} contains index of the <state> element currently in line for RNG
			uint64_t next();							//	Generate random 64 bits, increment the <index>, generate new <state> when needed
		public:
			//	Clone the state 
			//	Hashing function for seeding the RNG state
			//	<data> is supposed to be 64 bit (8 byte) aligned; <length> >= 8 (in bytes)
			//	WARNING: data is consumed in 64 bit chunks:
			//	...if <length> is not divisible by 8, the leftovers are not utilized
			void hash(const void* data, std::size_t length);

			uint64_t int64();			//	random 64 bits
			fp64_t U12();				//	Uniform[1,2)
			fp64_t U01();				//	Uniform[0,1]
			fp64_t N01();				//	Gaussian with 0 mean and variance 1 via rejection sampling
			fp64_t n01();				//	Another N(0,1) Gaussian via Box-Muller
	};
	

	/*------------------------------------------------------------------------------+
	 |																				|
	 | 	Mixers: fast hash functions producing "random" output from the <state>		|
	 |	These are not necessarily best for RNG when used to produce a sequence		|
	 |	of numbers: their primary purpose is to maximize bit mixing (avalanching)	|
	 |	after single use...															|
	 |																				|
	 +------------------------------------------------------------------------------*/


	uint8_t		mix8	(uint8_t state);
	uint16_t	mix16	(uint16_t state);
	uint32_t	mix32	(uint32_t state);
	uint64_t	mix64	(uint64_t state);
	


}

#endif
